apiVersion: apps/v1
kind: Deployment
metadata:
  name: springbootsecuritydb
  namespace: springbootsecuritydb
  labels:
    app: springbootsecuritydb
spec:
  replicas: 10
  selector:
    matchLabels:
      app: springbootsecuritydb
  template:
    metadata:
      labels:
        app: springbootsecuritydb
    spec:
      containers:
        - name: springbootsecuritydb
          image: ansalpandey/spring-security-db:latest
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: MONGO_DB_URI
            - name: MONGO_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-db-secret
                  key: MONGO_DB_NAME
