version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "D:/Work/Spring Boot/SpringSecurityDB/prometheus.yml:/etc/prometheus/prometheus.yml"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - "D:/Work/Spring Boot/SpringSecurityDB/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
    depends_on:
      - prometheus

  springsecuritydb:
    image: ansalpandey/spring-security-db:latest
    container_name: springsecuritydb
    ports:
      - "8080:8080"
    env_file:
      - .env

  consul:
    image: consul:1.15.4
    container_name: consul
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"
