kind: Service
apiVersion: v1
metadata:
  name: springbootsecuritydb
  namespace: springbootsecuritydb
  labels:
    app: springbootsecuritydb
spec:
    selector:
        app: springbootsecuritydb
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
    type: LoadBalancer